<?php

namespace Upc\Sunat\SunatBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DebtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DebtRepository extends EntityRepository {

    public function findAll() {
        $DQL = "SELECT d, p ,c
            FROM SunatBundle:Debt d
            JOIN d.person p
            JOIN d.concept c";
        $qb = $this->getEntityManager()->createQuery($DQL)
                ->setParameters(array());
        $re = $qb->getResult();
        return $re;
    }

    public function findbyRuc($ruc) {
        $DQL = "SELECT d, p ,c
            FROM SunatBundle:Debt d
            JOIN d.person p
            JOIN d.concept c WHERE p.ruc = :ruc";
        $qb = $this->getEntityManager()->createQuery($DQL)
                ->setParameters(array(
                    'ruc' => $ruc
                ));
        $debts = $qb->getResult();
        return $debts;
    }

}
