security:
    encoders:
        Upc\Sunat\SunatBundle\Entity\User:
            algorithm:        pbkdf2
            encode_as_base64: true
            iterations:       100

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
            entity: { class: SunatBundle:User, property: username }

    firewalls:                  
        login:
            pattern:  ^/admin/login$
            security: false

        secured_area:
            pattern:    ^/admin/
            form_login:
                check_path: _admin_security_check
                login_path: _admin_login
                always_use_default_target_path: true
                default_target_path: /admin
            logout:
                path:   _admin_logout
                target: _admin_login
                invalidate_session: false
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }